### ISSUE TITLE
Detecting OS on host during install

### ISSUE THREAD

**Issue by svanschalkwyk** [kbrebanov/ansible-java#3]
I use Mint on the laptop I'm using to install to Google Cloud. 
I pass the correct IPs from the GCE create script to the Java play book, but it seems to be looking for Linux Mint.yml on the laptop?

fatal: [35.184.195.129]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "failed": true, "message": "Could not find or access 'Linux Mint.yml'\nSearched in:\n\t/home/steph/Ansible/repos/ansible-java/vars/Linux Mint.yml\n\t/home/steph/Ansible/repos/ansible-java/Linux Mint.yml\n\t/home/steph/Ansible/repos/ansible-java/tasks/vars/Linux Mint.yml\n\t/home/steph/Ansible/repos/ansible-java/tasks/Linux Mint.yml\n\t/home/steph/Ansible/repos/compute-video-demo-ansible/vars/Linux Mint.yml\n\t/home/steph/Ansible/repos/compute-video-demo-ansible/Linux Mint.yml"}

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
